### PR TITLE
Changed deprecated data fields

### PR DESCRIPTION
**Pull request by DjilanoS**

### CODE REVIEW

**Comment by arjan-kwikqy** [comment]
+1, please merge asap! Thanks for the pull request

**Comment by DjilanoS** [comment]
@olefirenko Could your review and merge the pr?

**Comment by olefirenko** [comment]
@DjilanoS Merged and publish a new version on npm. Thank you for PR!

**Comment by DjilanoS** [comment]
@olefirenko Np, was a small fix. Thanks for merging!

**Comment by olefirenko** [comment]
@all-contributors please add @DjilanoS for submitting this PR

**Comment by olefirenko** [comment]
@all-contributors please add @DjilanoS for maintenance

**Pull request merged**
