### PR TITLE
change `types` to empty string  by default.

### PR DESCRIPTION
**Pull request by rowancollins89**
also sorted out the indentation as it was driving me crazy

### CODE REVIEW

**Comment by MichaelARoberts** [comment]
good pull. Types should be empty by default when I was wondering why it wasn't returning specific cities I had to read the docs for a while to figure out that you set a default. Google's own API has empty as a default as well, this feature just makes sense.

**Comment by olefirenko** [comment]
Thanks for PR.
I am not sure if it should be merged because for now a lot of people rely on default `types` config value as `address`, including in my own projects. So this PR will break their apps.
You can still pass empty `types` prop to get all data from the autocomplete
```html
<vue-google-autocomplete
    id="map"
    classname="form-control"
    placeholder="Start typing"
    v-on:placechanged="getAddressData"
    types=""
>
</vue-google-autocomplete>
```

**Comment by lmatab** [comment]
I was having problems with the type property too in order to get geo data from national parks

I see now that  this problem had been found by somebody else too.

**Comment by olefirenko** [comment]
Sorry! Have to close this PR, because of the issue with initial default value for `types`. Please take a look into my previous comment here https://github.com/olefirenko/vue-google-autocomplete/pull/44#issuecomment-348754965
Thanks for your time!

**Pull request closed without merging**
