### PR TITLE
Extract babel config to .babelrc

### PR DESCRIPTION
**Pull request by ankurk91**
### What was the issue?
You have specified babel config in `package.json`, when someone installs your package and build it through bundler like webpack. Webpack asks to install **babel-preset-es2015** package along. But not all user are using the same babel preset.

### How this PR solve this issue.
Extract the babel config to `.babelrc` file. 
This way your build tool should work as before but end users wont need to install the same babel preset as yours.
Also `.npmignore` prevent this file from publishing.

### CODE REVIEW

**Comment by olefirenko** [comment]
Thank you!

**Comment by ankurk91** [comment]
@olefirenko 
can you publish a  patch version so that I can update new build system.

**Comment by olefirenko** [comment]
Yes, just updated https://www.npmjs.com/package/vue-google-autocomplete

**Comment by ankurk91** [comment]
Many thanks.

**Pull request merged**
